### ISSUE TITLE
Record package sample data validation issues

### ISSUE THREAD

**Issue by mpostelnicu** [open-contracting/sample-data#82] opened 2018-10-02 13:10 UTC
Hi,

I am adding support for versioned release validation schema into https://github.com/devgateway/jocds (thanks a lot for supporting this work, btw!) and i found several validation issues with the sample data:

1. Versioned Release Classification ids are not versionable yet the sample data implies they are, this is the offending part:

https://github.com/open-contracting/sample-data/blob/e43d940ea587b78c57f7003a253c74f306acaff0/fictional-example/1.1/record/ocds-213czf-000-00001-withversions.json#L786

error reads:

```
{
  "level" : "error",
  "schema" : {
    "loadingURI" : "http://standard.open-contracting.org/schema/1__1__3/versioned-release-validation-schema.json#",
    "pointer" : "/definitions/Classification/properties/id"
  },
  "instance" : {
    "pointer" : "/records/0/versionedRelease/awards/0/items/0/classification/id"
  },
  "domain" : "validation",
  "keyword" : "type",
  "message" : "instance type (array) does not match any allowed primitive type (allowed: [\"integer\",\"null\",\"string\"])",
  "found" : "array",
  "expected" : [ "integer", "null", "string" ]
}
```

Classification scheme reads

https://github.com/open-contracting/standard/blob/b156dc33fecca61668a44f693b29db838c71000e/standard/schema/versioned-release-validation-schema.json#L1496

2. Versioned Release Units within Items, are version-aware arrays,  not objects:

https://github.com/open-contracting/sample-data/blob/e43d940ea587b78c57f7003a253c74f306acaff0/fictional-example/1.1/record/ocds-213czf-000-00001-withversions.json#L838

error reads:

```
{
  "level" : "error",
  "schema" : {
    "loadingURI" : "http://standard.open-contracting.org/schema/1__1__3/versioned-release-validation-schema.json#",
    "pointer" : "/definitions/Item/properties/unit"
  },
  "instance" : {
    "pointer" : "/records/0/versionedRelease/awards/0/items/0/unit"
  },
  "domain" : "validation",
  "keyword" : "type",
  "message" : "instance type (object) does not match any allowed primitive type (allowed: [\"array\"])",
  "found" : "object",
  "expected" : [ "array" ]
}
```
Unit definition within versioned item:

https://github.com/open-contracting/standard/blob/b156dc33fecca61668a44f693b29db838c71000e/standard/schema/versioned-release-validation-schema.json#L1339

Please let me know if these are indeed errors in example docs and how do u want to tackle them. i can do a PR and fix the samples if needed. 

Thanks!

**Comment by jpmckinney** [comment] 2018-11-09 19:50
Hi @mpostelnicu, we have some open issues with respect to `unit`. The behavior accidentally changed between 1.1.2 and 1.1.3, so we need to make a fix (either to the release schema, the versioned release schema, or the merging algorithm). I have it on my plate to resolve #737 #738 https://github.com/open-contracting/ocds-merge/pull/13 

As for classification `id`, I don't believe it should be versionable. I believe the commit that changed the behavior is 343d27475c03854e2ecb34e7f48637c31bbb2a0f cc @kindly to confirm that the classification id sample data is in error.

**Comment by mpostelnicu** [comment] 2018-11-26 13:33
hi @jpmckinney , jocds tests are failing. i was just about to release 0.4.0 when i noticed it and while investigating i came back to this ticket. thanks for fixing it, im checking to see what's wrong and will let u know.

**Comment by mpostelnicu** [comment] 2018-11-28 15:51
hi @jpmckinney i tested jocds versioned release  validation with this and we still have a few issues. one is here

https://github.com/open-contracting/sample-data/blob/master/fictional-example/1.1/record/ocds-213czf-000-00001-withversions.json#L2950

more exactly the id under `/records/0/versionedRelease/awards/0/items/0/classification/id` 

```
"id": [
                    {
                      "releaseID": "ocds-213czf-000-00001-04-award",
                      "releaseDate": "2010-05-10T09:30:00Z",
                      "releaseTag": [
                        "award"
                      ],
                      "value": "45233130.0"
                    }
                  ]
```

**Comment by jpmckinney** [comment] 2018-11-28 17:02
Indeed – I've made a PR (https://github.com/open-contracting/ocds-merge/pull/19) with a number of fixes to our implementation ([see changelog](https://github.com/open-contracting/ocds-merge/blob/2f0e192352f2f1d35847513f23bd818c5d4ff209/CHANGELOG.md)), but I haven't yet found the issue that produces this versioned ID. I should have it figured out this week, though.

**Comment by mpostelnicu** [comment] 2018-11-30 13:39
ok thanks @jpmckinney if u can please post a message here when the id issue is also fixed, ill make sure to fetch the final version and re-validate everything

**Comment by jpmckinney** [comment] 2018-11-30 13:52
Will do!

**Comment by jpmckinney** [comment] 2018-12-20 23:04
I've determined the cause, and opened an issue on the standard, where it will be more visible. https://github.com/open-contracting/standard/issues/798

I believe the sample-data is the correct behavior, and that the versioned release schema is incorrect. See linked issue for discussion.

Closing this issue to avoid confusion between which issue to contribute to.

**Closed by jpmckinney** 2018-12-20 23:04 UTC
